Module1 task3
htmlacademy-ecmascript/839417-cinemaddict-15 pull request #3
Opened 2021-07-28 19:29 UTC by Dimahtml

2021-07-28 20:41 UTC, andreevsm requested changes

2021-07-28 20:41 UTC, andreevsm commented on src/main.js
> +import {createOverallFilmsListContainer} from './view/overall-films-list-container.js';
Давай приведем названия к одному виду: лучше поменять в конце `Container` на `Template`, как в функциях выше. Все-таки мы создаем шаблон везде

2021-07-28 20:41 UTC, andreevsm commented on src/main.js
> +render(sortedFilmsList, createShowMoreTemplate(), 'beforeend');
Часто повторяется `beforeend`, предлагаю сделать его по умолчанию:
```
const render = (container, template, place = 'beforeend') => {
```

2021-07-29 14:32 UTC, Dimahtml commented on src/main.js
> +import {createOverallFilmsListContainer} from './view/overall-films-list-container.js';
готово

2021-07-29 14:33 UTC, Dimahtml commented on src/main.js
> +render(sortedFilmsList, createShowMoreTemplate(), 'beforeend');
сделал. но я все равно во всех случаях явно пишу необходимый аргумент.

2021-07-29 16:12 UTC, andreevsm requested changes

2021-07-29 16:12 UTC, andreevsm commented on src/main.js
> +render(sortedFilmsList, createShowMoreTemplate(), 'beforeend');
Так а зачем? Давай уберем, лишнее же получается)

2021-07-29 16:19 UTC, Dimahtml commented on src/main.js
> +render(sortedFilmsList, createShowMoreTemplate(), 'beforeend');
думал так будет лучше читаемость. ок, убрал дефолтные повторяющиеся значения

2021-07-29 21:41 UTC, merged