Module2 task1
htmlacademy-ecmascript/839417-cinemaddict-15 pull request #4
Opened 2021-08-08 09:06 UTC by Dimahtml

2021-08-08 13:23 UTC, andreevsm requested changes

2021-08-08 13:23 UTC, andreevsm commented on src/main.js
> +for (let i = 0; i < Math.min(films.length, FILMS_COUNT_PER_STEP); i++) {
Давай вынесем `Math.min(films.length, FILMS_COUNT_PER_STEP` в переменную выше
Просто этот код будет запускаться на каждую итерацию цикла, не очень производительно получается

2021-08-08 13:23 UTC, andreevsm commented on src/mock/film-mock.js
> +const MIN_DESCRIPTION_AMOUNT = 1;
Задумка с константами правильная, но в данном случае избыточна
1. Константа нигде во вне не используется, а здесь используется один раз
2. Какое нам дело до рандомного числа? Функция запустилась, сгенерировала массив описаний. А сколько она сгенерировала объектов нам без разницы, ну то есть мы нигде не учитываем длинну массива

Поэтому можно смело хардкодить такие цифры внутри функции:
```
const dateSubtract = getRandomInteger(10, 30000);
```

2021-08-08 13:23 UTC, andreevsm commented on src/mock/films-statistic-mock.js
> +  let result = getRandomInteger(MIN_FILMS_AMOUNT, MAX_FILMS_AMOUNT);
Давай заменим на const:
```
const result = getRandomInteger(MIN_FILMS_AMOUNT, MAX_FILMS_AMOUNT).toString();

return result...
```

2021-08-08 13:23 UTC, andreevsm commented on src/view/film-details.js
> +    let commentDay = '';
Давай вынесем определение дня в отдельную функцию

2021-08-08 13:34 UTC, Dimahtml commented on src/mock/film-mock.js
> +const MIN_DESCRIPTION_AMOUNT = 1;
да, я написал очень много констант. так легче делать рефакторинг, тестирование, отладку. эту убираю =)

2021-08-08 13:36 UTC, Dimahtml commented on src/mock/film-mock.js
> +const MIN_DESCRIPTION_AMOUNT = 1;
речь ведь об одной константе, не о всех?

2021-08-09 15:18 UTC, andreevsm requested changes

2021-08-09 15:21 UTC, Dimahtml commented on src/mock/film-mock.js
> +const MIN_DESCRIPTION_AMOUNT = 1;
так эти константы для моковых данных. их все равно скоро удалять надо будет... может пока оставим?

2021-08-09 16:18 UTC, merged